### PR TITLE
changing the input of discriminator

### PR DESCRIPTION
**Pull request by whoosher**
adjusting the same channel as output of generator for favorable training

### CODE REVIEW

**Review by black0017 — COMMENTED** [review]
Ok nice. Can you please only include the change in `models/GAN3D.py` ?

There are some files (`.idea`) from your editor.

Best,

N.

**Comment by whoosher** [comment]
Oops, sorry for that. 
I'll change that in tomorrow, asap.
Thanks for the beautiful code about 3D-GAN. I was really impressed by your code.
Best regard, have a nice day.

**Review by whoosher — COMMENTED** [review]
changing dimension of the discriminator and delete my files

**Review by black0017 — APPROVED** [review]
Thanks for cleaning that up.
N.

**Pull request merged**
